version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-dev
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - mongo-network
    volumes:
      - type: volume
        source: mongo-volume
        target: "/data/db"
        read_only: false

  mongo-express:
    image: mongo-express
    container_name: mongo-express-dev
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-dev:27017/
    networks:
      - mongo-network

networks:
  mongo-network:
    name: mongo-network
    driver: bridge

volumes:
  mongo-volume:
    name: mongo-volume
